# Generated by Django 5.0.1 on 2024-01-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Picture')),
                ('description', models.TextField()),
                ('size', models.CharField(max_length=200)),
                ('predominant_color', models.CharField(max_length=200)),
                ('average_color', models.CharField(max_length=200)),
                ('color_palette', models.CharField(max_length=200)),
            ],
        ),
    ]
