# Generated by Django 5.0.1 on 2024-01-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color1', models.CharField(max_length=7)),
                ('color2', models.CharField(max_length=7)),
                ('color3', models.CharField(max_length=7)),
                ('color4', models.CharField(max_length=7)),
                ('color5', models.CharField(max_length=7)),
                ('color6', models.CharField(max_length=7)),
                ('color7', models.CharField(max_length=7)),
                ('color8', models.CharField(max_length=7)),
                ('color9', models.CharField(max_length=7)),
                ('color10', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ImageField(upload_to='img/')),
                ('description', models.TextField()),
                ('size', models.CharField(max_length=20)),
                ('predominant_color', models.CharField(max_length=7)),
                ('average_color', models.CharField(max_length=7)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
