# Generated by Django 5.0.1 on 2024-01-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='content',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
