# Generated by Django 5.0.1 on 2024-01-09 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='average_color',
        ),
        migrations.RemoveField(
            model_name='image',
            name='predominant_color',
        ),
        migrations.RemoveField(
            model_name='image',
            name='size',
        ),
        migrations.DeleteModel(
            name='ColorPalette',
        ),
    ]
