# Generated by Django 5.0.1 on 2024-01-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_remove_image_average_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='content',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Picture'),
        ),
    ]
